In [3]:
import csv
import time 
import pandas as pd

############ ELAPSED TIME ############
# st = time.time()


############ DATA PREPERATION ############
with open('data.csv', newline='') as f:
    reader = csv.reader(f)
    data = list(reader)
    
play_id = []
song_id = []
client_id =[]
play_ts = []

for i in range(len(data)):
    try:
        play_id.append(data[i][0].split('\t')[0])
        song_id.append(data[i][0].split('\t')[1])
        client_id.append(data[i][0].split('\t')[2])
        play_ts.append(data[i][0].split('\t')[3].split(' ')[0])
        
    except IndexError:
        continue
    
    
play_id = play_id[1:]
song_id = song_id[1:]
client_id = client_id[1:]
play_ts = play_ts[1:]


df = pd.DataFrame(list(zip(play_id, song_id, client_id,play_ts)), columns = ['play_id', 'song_id','client_id','play_ts'])


############ DATE FILTERING ############ 
filtered_df = df[df['play_ts'] == '10/08/2016']

############ GROUP BY CLIENTS AND COUNT THE NUMBER OF DISTINCT SONGS PLAYED ############ 
client_distinct = filtered_df.groupby('client_id').agg({'song_id': 'nunique'}).reset_index()
client_distinct = client_distinct.rename(columns={'song_id': 'DistinctSongCount'})

############ GROUP BY NUMBER OF DISTINCT SONGS PLAYED AND COUNT NUMBER OF USERS ############ 
client_distinct = client_distinct.groupby('DistinctSongCount')['client_id'].nunique().to_frame()
client_distinct = client_distinct.rename(columns={'client_id': 'ClientCount'})

############ ELAPSED TIME ############
# end = time.time()
# print('elapsed time {}'.format(end-st))

In [4]:
client_distinct

                   ClientCount
DistinctSongCount
8                            1
9                            1
10                           3
11                           1
12                          15
13                          19
14                          23
15                          46
16                          51
17                          68
18                          90
19                          82
20                          95
21                          77
22                          96
23                          79
24                          57
25                          61
26                          42
27                          24
28                          23
29                          12
30                          11
31                           7
32                           3
33                           4
34                           4
35                           1
36                           1
37                           1
38                           1